### ISSUE TITLE
Current status + move to r-spatial

### ISSUE THREAD

**Issue by pat-s** [fapola/RPyGeo#1]
Hi @fapola,

whats the current state of the update?

If its close to be finished, it would be great if we could move the repo to the r-spatial org. We also recently moved `RSAGA` there. `RQGIS` might follow.

**Comment by fapola** [comment]
Hi @pat-s ,
I would love to move the repo to r-spatial. However, I still want to change and clarify some things to make it easier for others to collaborate. I think we can move it during the next couple of weeks and I will let you know as soon as I am ready.

**Comment by pat-s** [comment]
Great! Simply open an issue in `r-spatial/discuss` once you are ready.

**Comment by fapola** [comment]
Unfortunately, I currently have no time to work on the RPyGeo Package. @be-marc can you move it to r-spatial once you are ready?

**Comment by be-marc** [comment]
Yes I will move it later

**Comment by be-marc** [comment]
https://github.com/r-spatial/discuss/issues/22
