### ISSUE TITLE
64 bit computer

### ISSUE THREAD

**Issue by thom1253** [fapola/RPyGeo#7]
I'm by no means a computer wizard, so maybe this is an easy problem. I was excited to find your package as I'm familiar with R and ArcGIS and like elements of each (R language and repeatability, arcGIS speed). When I tried to start running your package, I got this error:
_Error in initialize_python(required_module, use_environment) : 
  Your current architecture is 64bit however this version of Python is compiled for 32bit._

Any suggestions?
Thank you!
Sarah

**Comment by fapola** [comment]
Hi Sarah, 
sorry for my late reply. It seems like you are using a 32-bit Python version and a 64-bit R version. Python and R need to have the same architecture. 
Cheers,
Fabian

**Comment by thom1253** [comment]
OK, I had been trying to point it to a different build of python (but it seems to want the arcmap loaded version), but I'll try switching to 32 bit version of R... I don't know why that didn't occur to me.
